# Generated by Django 3.2.23 on 2023-11-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
